/*
 * This source file was generated by the Gradle 'init' task
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-unit-nov-20 using AI Type Claude AI and AI Model claude-haiku-4-5-20251001

ROOST_METHOD_HASH=split_bb571da59d
ROOST_METHOD_SIG_HASH=split_305be1a212

Scenario 1: Split a Standard String with Whitespace Delimiters

Details:
  TestName: splitStandardStringWithWhitespace
  Description: This test verifies that the split method correctly divides a standard string containing multiple words separated by whitespace into individual elements within a LinkedList. The test ensures that the method properly handles typical input scenarios where words are separated by spaces.

Execution:
  Arrange: Create a test string with multiple words separated by single spaces, such as "Hello World Java Programming".
  Act: Invoke the split method with the prepared string as the source parameter.
  Assert: Verify that the returned LinkedList contains exactly four elements with values "Hello", "World", "Java", and "Programming" in the correct order.

Validation:
  The assertion validates that the split method correctly identifies whitespace as a delimiter and separates the string into individual words. This is fundamental functionality that ensures the method works as expected for common use cases. The test confirms that the LinkedList maintains the order of elements and contains the correct number of items.

*/

// ********RoostGPT********

package org.example.utilities;
import org.example.list.LinkedList;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;

@DisplayName("StringUtils Split Method Tests")
class StringUtilsSplitTest {
    @Test
    @Tag("valid")
    @DisplayName("Split standard string with whitespace delimiters")
    void splitStandardStringWithWhitespace() {
        // Arrange
        String source = "Hello World Java Programming";
        
        // Act
        LinkedList result = StringUtils.split(source);
        
        // Assert
        assertNotNull(result, "Result should not be null");
        assertEquals(4, result.size(), "LinkedList should contain 4 elements");
        assertEquals("Hello", result.get(0), "First element should be 'Hello'");
        assertEquals("World", result.get(1), "Second element should be 'World'");
        assertEquals("Java", result.get(2), "Third element should be 'Java'");
        assertEquals("Programming", result.get(3), "Fourth element should be 'Programming'");
    }
    @Test
    @Tag("valid")
    @DisplayName("Split string with single word")
    void splitSingleWord() {
        // Arrange
        String source = "Hello";
        
        // Act
        LinkedList result = StringUtils.split(source);
        
        // Assert
        assertNotNull(result, "Result should not be null");
        assertEquals(1, result.size(), "LinkedList should contain 1 element");
        assertEquals("Hello", result.get(0), "Element should be 'Hello'");
    }
    @Test
    @Tag("valid")
    @DisplayName("Split string with multiple spaces between words")
    void splitStringWithMultipleSpaces() {
        // Arrange
        String source = "Hello    World   Java";
        
        // Act
        LinkedList result = StringUtils.split(source);
        
        // Assert
        assertNotNull(result, "Result should not be null");
        assertTrue(result.size() >= 3, "LinkedList should contain at least 3 elements");
        assertEquals("Hello", result.get(0), "First element should be 'Hello'");
        assertEquals("World", result.get(result.size() - 2), "Second to last should be 'World'");
        assertEquals("Java", result.get(result.size() - 1), "Last element should be 'Java'");
    }
    @Test
    @Tag("valid")
    @DisplayName("Split string with leading whitespace")
    void splitStringWithLeadingWhitespace() {
        // Arrange
        String source = "   Hello World";
        
        // Act
        LinkedList result = StringUtils.split(source);
        
        // Assert
        assertNotNull(result, "Result should not be null");
        assertTrue(result.size() >= 2, "LinkedList should contain at least 2 elements");
        assertEquals("Hello", result.get(result.size() - 2), "Should contain 'Hello'");
        assertEquals("World", result.get(result.size() - 1), "Should contain 'World'");
    }
    @Test
    @Tag("valid")
    @DisplayName("Split string with trailing whitespace")
    void splitStringWithTrailingWhitespace() {
        // Arrange
        String source = "Hello World   ";
        
        // Act
        LinkedList result = StringUtils.split(source);
        
        // Assert
        assertNotNull(result, "Result should not be null");
        assertTrue(result.size() >= 2, "LinkedList should contain at least 2 elements");
        assertEquals("Hello", result.get(0), "First element should be 'Hello'");
        assertEquals("World", result.get(1), "Second element should be 'World'");
    }
    @Test
    @Tag("boundary")
    @DisplayName("Split empty string")
    void splitEmptyString() {
        // Arrange
        String source = "";
        
        // Act
        LinkedList result = StringUtils.split(source);
        
        // Assert
        assertNotNull(result, "Result should not be null");
        assertEquals(0, result.size(), "LinkedList should be empty");
    }
    @Test
    @Tag("boundary")
    @DisplayName("Split string with only whitespace")
    void splitStringWithOnlyWhitespace() {
        // Arrange
        String source = "     ";
        
        // Act
        LinkedList result = StringUtils.split(source);
        
        // Assert
        assertNotNull(result, "Result should not be null");
        assertEquals(0, result.size(), "LinkedList should be empty");
    }
    @Test
    @Tag("invalid")
    @DisplayName("Split null string")
    void splitNullString() {
        // Arrange
        String source = null;
        
        // Act & Assert
        assertThrows(NullPointerException.class, () -> {
            StringUtils.split(source);
        }, "Should throw NullPointerException for null input");
    }
    @Test
    @Tag("valid")
    @DisplayName("Split string with tabs and newlines")
    void splitStringWithMixedWhitespace() {
        // Arrange
        String source = "Hello\tWorld\nJava";
        
        // Act
        LinkedList result = StringUtils.split(source);
        
        // Assert
        assertNotNull(result, "Result should not be null");
        assertTrue(result.size() >= 3, "LinkedList should contain at least 3 elements");
    }
    @Test
    @Tag("valid")
    @DisplayName("Split string with special characters")
    void splitStringWithSpecialCharacters() {
        // Arrange
        String source = "Hello@123 World#456 Java$789";
        
        // Act
        LinkedList result = StringUtils.split(source);
        
        // Assert
        assertNotNull(result, "Result should not be null");
        assertEquals(3, result.size(), "LinkedList should contain 3 elements");
        assertEquals("Hello@123", result.get(0), "First element should be 'Hello@123'");
        assertEquals("World#456", result.get(1), "Second element should be 'World#456'");
        assertEquals("Java$789", result.get(2), "Third element should be 'Java$789'");
    }
    @Test
    @Tag("valid")
    @DisplayName("Split string with numbers")
    void splitStringWithNumbers() {
        // Arrange
        String source = "123 456 789";
        
        // Act
        LinkedList result = StringUtils.split(source);
        
        // Assert
        assertNotNull(result, "Result should not be null");
        assertEquals(3, result.size(), "LinkedList should contain 3 elements");
        assertEquals("123", result.get(0), "First element should be '123'");
        assertEquals("456", result.get(1), "Second element should be '456'");
        assertEquals("789", result.get(2), "Third element should be '789'");
    }
    @Test
    @Tag("valid")
    @DisplayName("Split string with mixed case")
    void splitStringWithMixedCase() {
        // Arrange
        String source = "HeLLo WoRLd JaVa";
        
        // Act
        LinkedList result = StringUtils.split(source);
        
        // Assert
        assertNotNull(result, "Result should not be null");
        assertEquals(3, result.size(), "LinkedList should contain 3 elements");
        assertEquals("HeLLo", result.get(0), "First element should preserve case");
        assertEquals("WoRLd", result.get(1), "Second element should preserve case");
        assertEquals("JaVa", result.get(2), "Third element should preserve case");
    }
    @Test
    @Tag("valid")
    @DisplayName("Split long string with many words")
    void splitLongStringWithManyWords() {
        // Arrange
        String source = "The quick brown fox jumps over the lazy dog";
        
        // Act
        LinkedList result = StringUtils.split(source);
        
        // Assert
        assertNotNull(result, "Result should not be null");
        assertEquals(9, result.size(), "LinkedList should contain 9 elements");
        assertEquals("The", result.get(0), "First element should be 'The'");
        assertEquals("dog", result.get(8), "Last element should be 'dog'");
    }
    @Test
    @Tag("valid")
    @DisplayName("Split string with hyphenated words")
    void splitStringWithHyphenatedWords() {
        // Arrange
        String source = "well-known high-quality state-of-the-art";
        
        // Act
        LinkedList result = StringUtils.split(source);
        
        // Assert
        assertNotNull(result, "Result should not be null");
        assertEquals(3, result.size(), "LinkedList should contain 3 elements");
        assertEquals("well-known", result.get(0), "First element should be 'well-known'");
        assertEquals("high-quality", result.get(1), "Second element should be 'high-quality'");
        assertEquals("state-of-the-art", result.get(2), "Third element should be 'state-of-the-art'");
    }
    @Test
    @Tag("valid")
    @DisplayName("Split string preserves order of elements")
    void splitStringPreservesOrder() {
        // Arrange
        String source = "First Second Third Fourth Fifth";
        
        // Act
        LinkedList result = StringUtils.split(source);
        
        // Assert
        assertNotNull(result, "Result should not be null");
        assertEquals(5, result.size(), "LinkedList should contain 5 elements");
        for (int i = 0; i < result.size(); i++) {
            assertNotNull(result.get(i), "Element at index " + i + " should not be null");
        }
        assertEquals("First", result.get(0), "Order should be preserved");
        assertEquals("Fifth", result.get(4), "Order should be preserved");
    }
    @ParameterizedTest
    @CsvSource({
        "'Hello World', 2",
        "'One Two Three', 3",
        "'A B C D E', 5",
        "'Single', 1"
    })
    @Tag("valid")
    @DisplayName("Split various strings with different word counts")
    void splitVariousStringsParameterized(String source, int expectedSize) {
        // Act
        LinkedList result = StringUtils.split(source);
        
        // Assert
        assertNotNull(result, "Result should not be null");
        assertEquals(expectedSize, result.size(), "LinkedList should contain " + expectedSize + " elements");
    }
    @Test
    @Tag("valid")
    @DisplayName("Split string with unicode characters")
    void splitStringWithUnicodeCharacters() {
        // Arrange
        String source = "Héllo Wørld Jåva";
        
        // Act
        LinkedList result = StringUtils.split(source);
        
        // Assert
        assertNotNull(result, "Result should not be null");
        assertEquals(3, result.size(), "LinkedList should contain 3 elements");
        assertEquals("Héllo", result.get(0), "First element should be 'Héllo'");
    }
    @Test
    @Tag("valid")
    @DisplayName("Split string result is not null")
    void splitStringResultNotNull() {
        // Arrange
        String source = "Test String";
        
        // Act
        LinkedList result = StringUtils.split(source);
        
        // Assert
        assertNotNull(result, "Result LinkedList should never be null");
    }
    @Test
    @Tag("valid")
    @DisplayName("Split string with repeated words")
    void splitStringWithRepeatedWords() {
        // Arrange
        String source = "test test test";
        
        // Act
        LinkedList result = StringUtils.split(source);
        
        // Assert
        assertNotNull(result, "Result should not be null");
        assertEquals(3, result.size(), "LinkedList should contain 3 elements");
        assertEquals("test", result.get(0), "All elements should be 'test'");
        assertEquals("test", result.get(1), "All elements should be 'test'");
        assertEquals("test", result.get(2), "All elements should be 'test'");
    }
}