/*
 * This source file was generated by the Gradle 'init' task
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test Nov19-gradle using AI Type Gemini AI and AI Model gemini-2.5-pro-preview-03-25

ROOST_METHOD_HASH=get_0d973ea47e
ROOST_METHOD_SIG_HASH=get_c2afb2c160

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/Nov19-gradle/7372edef-0a52-4b69-9467-be15b4241d3a/source/gradle-app/list/src/test/java/org/example/list/LinkedListTest.java
Tests:
    "@Test
void testAdd() {
    LinkedList list = new LinkedList();
    list.add("one");
    assertEquals(1, list.size());
    assertEquals("one", list.get(0));
    list.add("two");
    assertEquals(2, list.size());
    assertEquals("two", list.get(1));
}
"
    "@Test
void testRemove() {
    LinkedList list = new LinkedList();
    list.add("one");
    list.add("two");
    assertTrue(list.remove("one"));
    assertEquals(1, list.size());
    assertEquals("two", list.get(0));
    assertTrue(list.remove("two"));
    assertEquals(0, list.size());
}
"Scenario 1: Retrieve the first element from a list with multiple items

Details:  
  TestName: getFirstElementFromMultiItemList
  Description: This test verifies that the `get` method can correctly retrieve the element at index 0 (the head of the list) when the list contains more than one element.
Execution:
  Arrange: Create a new `LinkedList` instance. Use the `add` method to insert three elements: "Apple", "Banana", and "Cherry".
  Act: Invoke the `get` method with an index of 0.
  Assert: Assert that the returned string is equal to "Apple".
Validation: 
  This scenario validates the basic functionality of retrieving the first element. It ensures the loop condition `index > 0` is handled correctly for index 0, and the head node's data is returned as expected.

---
Scenario 2: Retrieve an element from the middle of the list

Details:  
  TestName: getMiddleElementFromList
  Description: This test ensures that the `get` method can traverse the list and retrieve an element from a position between the head and the tail.
Execution:
  Arrange: Create a new `LinkedList` instance. Add three elements: "Apple", "Banana", and "Cherry".
  Act: Invoke the `get` method with an index of 1.
  Assert: Assert that the returned string is equal to "Banana".
Validation: 
  This test confirms that the internal loop correctly iterates through the list by decrementing the index and advancing the node pointer until the target index is reached.

---
Scenario 3: Retrieve the last element from the list

Details:  
  TestName: getLastElementFromList
  Description: This test verifies that the `get` method can correctly retrieve the last element of the list.
Execution:
  Arrange: Create a new `LinkedList` instance. Add three elements: "Apple", "Banana", and "Cherry".
  Act: Invoke the `get` method with an index of 2 (the last valid index).
  Assert: Assert that the returned string is equal to "Cherry".
Validation: 
  This scenario validates that the traversal logic works correctly up to the very end of the list and returns the data from the final node for the given index.

---
Scenario 4: Retrieve the only element from a single-item list

Details:  
  TestName: getElementFromSingleItemList
  Description: This test checks the behavior of the `get` method on a list that contains only one element.
Execution:
  Arrange: Create a new `LinkedList` instance and add a single element, "Apple".
  Act: Invoke the `get` method with an index of 0.
  Assert: Assert that the returned string is equal to "Apple".
Validation: 
  This is an edge case test to ensure that the method works correctly for the smallest possible non-empty list, where the first and last element are the same.

---
Scenario 5: Attempt to retrieve an element from an empty list

Details:  
  TestName: getElementFromEmptyListThrowsException
  Description: This test ensures that calling `get` on an empty list throws an `IndexOutOfBoundsException`.
Execution:
  Arrange: Create a new, empty `LinkedList` instance.
  Act: Invoke the `get` method with an index of 0.
  Assert: Assert that an `IndexOutOfBoundsException` is thrown.
Validation: 
  This test validates the error handling for an empty list. The `head` is null, so the iterator `it` starts as null, causing the exception to be thrown as expected, preventing a `NullPointerException`.

---
Scenario 6: Attempt to retrieve an element with an index equal to the list size

Details:  
  TestName: getElementAtIndexEqualToSizeThrowsException
  Description: This test verifies that an `IndexOutOfBoundsException` is thrown when the requested index is equal to the size of the list, as indices are zero-based.
Execution:
  Arrange: Create a new `LinkedList` instance and add two elements, "Apple" and "Banana". The size is 2, so valid indices are 0 and 1.
  Act: Invoke the `get` method with an index of 2.
  Assert: Assert that an `IndexOutOfBoundsException` is thrown.
Validation: 
  This scenario confirms the boundary condition check. The loop will terminate when the iterator `it` becomes null after passing the last element, correctly triggering the exception.

---
Scenario 7: Attempt to retrieve an element with an index greater than the list size

Details:  
  TestName: getElementAtInvalidIndexGreaterThanSizeThrowsException
  Description: This test ensures that requesting an index far beyond the list's bounds results in an `IndexOutOfBoundsException`.
Execution:
  Arrange: Create a new `LinkedList` instance and add two elements, "Apple" and "Banana".
  Act: Invoke the `get` method with a large index, such as 10.
  Assert: Assert that an `IndexOutOfBoundsException` is thrown.
Validation: 
  This test validates the robustness of the method's error handling for out-of-range indices, ensuring it doesn't enter an infinite loop or cause other unexpected errors.

---
Scenario 8: Attempt to retrieve an element with a negative index from a non-empty list

Details:  
  TestName: getElementAtNegativeIndexFromNonEmptyList
  Description: This test checks the behavior of the method when a negative index is provided. Based on the current implementation, the `while (index > 0)` loop will not execute, and the method will return the data of the head element.
Execution:
  Arrange: Create a new `LinkedList` instance and add elements "Apple", "Banana", and "Cherry".
  Act: Invoke the `get` method with an index of -1.
  Assert: Assert that the returned string is "Apple".
Validation: 
  This scenario highlights a potential flaw in the implementation. Standard list implementations would throw an `IndexOutOfBoundsException` for negative indices. This test verifies the actual, albeit likely incorrect, behavior of the provided code.

---
Scenario 9: Attempt to retrieve an element with a negative index from an empty list

Details:  
  TestName: getElementAtNegativeIndexFromEmptyListThrowsException
  Description: This test verifies that an `IndexOutOfBoundsException` is thrown when a negative index is used to access an empty list.
Execution:
  Arrange: Create a new, empty `LinkedList` instance.
  Act: Invoke the `get` method with an index of -1.
  Assert: Assert that an `IndexOutOfBoundsException` is thrown.
Validation: 
  This test confirms that even with a negative index, the initial check for a null iterator (`it == null`) correctly handles the empty list case and throws the appropriate exception.

*/

// ********RoostGPT********

package org.example.list;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.*;

public class LinkedListGetTest {
    private LinkedList linkedList;
    @BeforeEach
    public void setUp() {
        linkedList = new LinkedList();
    }
    @Test
    @Tag("valid")
    public void getFirstElementFromMultiItemList() {
        linkedList.add("Apple");
        linkedList.add("Banana");
        linkedList.add("Cherry");
        String result = linkedList.get(0);
        assertEquals("Apple", result);
    }
    @Test
    @Tag("valid")
    public void getMiddleElementFromList() {
        linkedList.add("Apple");
        linkedList.add("Banana");
        linkedList.add("Cherry");
        String result = linkedList.get(1);
        assertEquals("Banana", result);
    }
    @Test
    @Tag("valid")
    public void getLastElementFromList() {
        linkedList.add("Apple");
        linkedList.add("Banana");
        linkedList.add("Cherry");
        String result = linkedList.get(2);
        assertEquals("Cherry", result);
    }
    @Test
    @Tag("boundary")
    public void getElementFromSingleItemList() {
        linkedList.add("Apple");
        String result = linkedList.get(0);
        assertEquals("Apple", result);
    }
    @Test
    @Tag("invalid")
    public void getElementFromEmptyListThrowsException() {
        assertThrows(IndexOutOfBoundsException.class, () -> {
            linkedList.get(0);
        });
    }
    @Test
    @Tag("boundary")
    public void getElementAtIndexEqualToSizeThrowsException() {
        linkedList.add("Apple");
        linkedList.add("Banana");
        assertThrows(IndexOutOfBoundsException.class, () -> {
            linkedList.get(2);
        });
    }
    @Test
    @Tag("invalid")
    public void getElementAtInvalidIndexGreaterThanSizeThrowsException() {
        linkedList.add("Apple");
        linkedList.add("Banana");
        assertThrows(IndexOutOfBoundsException.class, () -> {
            linkedList.get(10);
        });
    }
    @Test
    @Tag("invalid")
    public void getElementAtNegativeIndexFromNonEmptyList() {
        linkedList.add("Apple");
        linkedList.add("Banana");
        linkedList.add("Cherry");
        String result = linkedList.get(-1);
        assertEquals("Apple", result);
    }
    @Test
    @Tag("invalid")
    public void getElementAtNegativeIndexFromEmptyListThrowsException() {
        assertThrows(IndexOutOfBoundsException.class, () -> {
            linkedList.get(-1);
        });
    }
}