
// ********RoostGPT********
/*
Test generated by RoostGPT for test oct22-gradle using AI Type Gemini AI and AI Model gemini-2.5-pro-preview-03-25
ROOST_METHOD_HASH=getAllCustomers_616ec51832
ROOST_METHOD_SIG_HASH=getAllCustomers_779982ffd6
Scenario 1: Verify successful retrieval of a list of customers
Details:
  TestName: getAllCustomersReturnsListOfCustomersSuccessfully
  Description: This test ensures that the `getAllCustomers` method correctly retrieves and returns a list of customers when the service layer provides a non-empty list.
Execution:
  Arrange: Mock the `CustomerService`. Create a list containing multiple `Customer` objects. Configure the mock `customerService.getAllCustomers()` method to return this list.
  Act: Invoke the `getAllCustomers()` method on the `CustomerController` instance.
  Assert: Assert that the returned `List<Customer>` is not null. Verify that the size of the returned list matches the size of the list provided by the mock service. Confirm that the content of the returned list is identical to the mocked list.
Validation:
  This scenario validates the primary success path of the endpoint. It confirms that the controller correctly delegates the call to the service layer and returns the fetched data to the client without modification.
*/
// ********RoostGPT********
package com.example.demo.web;
import com.example.demo.domain.Customer;
import com.example.demo.service.CustomerService;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.when;
import org.springframework.web.bind.annotation.*;
import java.util.Optional;
import org.junit.jupiter.api.*;

@Tag("com.example.demo.web")
@Tag("com.example.demo.web.getAllCustomers")
@ExtendWith(MockitoExtension.class)
class CustomerControllerGetAllCustomersTest {
    @Mock
    private CustomerService customerService;
    @InjectMocks
    private CustomerController customerController;
    @Test
    void getAllCustomersReturnsListOfCustomersSuccessfully() {
        // Arrange
        Customer customer1 = new Customer();
        customer1.setId(1L);
        customer1.setName("John Doe");
        customer1.setEmail("john.doe@example.com");
        Customer customer2 = new Customer();
        customer2.setId(2L);
        customer2.setName("Jane Doe");
        customer2.setEmail("jane.doe@example.com");
        List<Customer> expectedCustomers = Arrays.asList(customer1, customer2);
        when(customerService.getAllCustomers()).thenReturn(expectedCustomers);
        // Act
        List<Customer> actualCustomers = customerController.getAllCustomers();
        // Assert
        assertNotNull(actualCustomers);
        assertEquals(2, actualCustomers.size());
        assertEquals(expectedCustomers, actualCustomers);
    }
    @Test
    void getAllCustomersReturnsEmptyListWhenNoCustomers() {
        // Arrange
        when(customerService.getAllCustomers()).thenReturn(Collections.emptyList());
        // Act
        List<Customer> actualCustomers = customerController.getAllCustomers();
        // Assert
        assertNotNull(actualCustomers);
        assertEquals(0, actualCustomers.size());
    }
}